name=input("Name: ")
dep=input("Department: ")
year=input("Year: ")
semester=input("Semester: ")
section=input("Section: ")
roll=input("Roll Number: ")
s1=float(input("Enter marks for subjekt 1: "))
s2=float(input("Enter marks for subject 2: "))
s3=float(input("Enter marks for subject 3: "))
s4=float(input("Enter marks for subject 4: "))
s5=float(input("Enter marks for subject 5: "))
total=(s1+s2+s3+s4+s5)
per=(total/5)

print("STUDENT MARKSHEET")
print("Name:", name)
print("Department:", dep)
print("Year:", year)
print("Semester:", semester)
print("Section:", section)
print("Roll Number:", roll)
print("Subject 1 Marks:", s1)
print("Subject 2 Marks:", s2)
print("Subject 3 Marks:", s3)
print("Subject 4 Marks:", s4)
print("Subject 5 Marks:", s5)
print("Total Marks:", total)
print(f"Percentage: {per:.2f}%")